### ISSUE TITLE
strange statusbar msg with Java server

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#101]
![j-er](https://user-images.githubusercontent.com/4154978/198353580-b694921a-9732-47d0-8479-1b2dba4a0775.png)

@veksha

**Comment by veksha** [comment]
this is non-standard.
I think this is used by vscode extension to show loading progress.

from https://www.eclipse.org/community/eclipse_newsletter/2017/may/article4.php :

- <i>jdt.ls also enhances the default Language Server Protocol by adding specific messages:
language/status
language/actionableNotification
java/classFileContents
java/projectConfigurationUpdate
</i>

**Comment by Alexey-T** [comment]
Ok, tks.
