### ISSUE TITLE
Java server completions - some funcs don't have '()' and no gray highlight for func result

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#102]
![j-list](https://user-images.githubusercontent.com/4154978/198354068-09207421-848b-48a3-b5f3-b25c94529f58.png)

@veksha

**Comment by Alexey-T** [comment]
line 665 in this file,

[SmallSortedMap.zip](https://github.com/CudaText-addons/cuda_lsp/files/9881670/SmallSortedMap.zip)


`      h += entry|List.get(i).hashCode();`

**Comment by veksha** [comment]
I see only one method on screenshot

**Comment by Alexey-T** [comment]
ah, okay.
