### ISSUE TITLE
strange err msg in console when I work with py files

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#105]
```
Loaded session: "history session.json", 10ms, 2 file(s)
LSP: starting server - Python; root: /home/user/.config/cudatext/settings/lsp_v.json
NOTE: LSP: Python - Failed to create process, command: ['pylsp']; Error: [Errno 20] Not a directory: '/home/user/.config/cudatext/settings/lsp_v.json'
```

lsp_v.json is one of recent files - i didnt use it for 1 day at all. i even didn't load this file in this session.

**Comment by Alexey-T** [comment]
aha!! lsp_v.json is the FIRST FILE IN THE PROJECT! SINGLE FILE!

![Screenshot from 2022-10-28 00-09-19](https://user-images.githubusercontent.com/4154978/198398597-b757004b-5112-4ced-ae68-3ad9626cff0f.png)

**Comment by veksha** [comment]
I noticed on your screenshots that sometimes your "root" is None or empty.
but on my Windows system i can't set root to None because even if I call `project file -> new project` it will switch to temporary project (which has the following path: F:\MySSDPrograms\cudatext\settings)

**Comment by veksha** [comment]
I don't know how you managed to set project root to a file and not a folder.

**Comment by Alexey-T** [comment]
fixed! I just pressed 'file' icon in proj-man and added a file
