### ISSUE TITLE
Scala server

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#106]
1. install Coursier: https://get-coursier.io/docs/cli-installation
2. install Metals: `cs install metals`

Config for Windows:
```json
{
  "lexers": {
    "Scala": "scala"
  },
  "cmd_windows": ["metals.bat"]
}
```

test file:
```scala
object Hello extends App {
    println("Hello, world")
}
```

PS: install Scala lexer in CudaText

**Comment by Alexey-T** [comment]
Posted to wiki https://wiki.freepascal.org/CudaText_plugins#LSP_server_for_Scala

Tks!
