### ISSUE TITLE
scala server autocompletion issue

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#115]
https://user-images.githubusercontent.com/275333/201997045-5d05a589-902e-4366-b03e-c7ddb65d144a.mp4

**Comment by veksha** [comment]
Hi @Alexey-T, please test branch: https://github.com/veksha/cuda_lsp/tree/reworked_completion
reworked autocompletion and added "unit tests", in order to avoid regressions.

**Comment by Alexey-T** [comment]
played with it. on D, C++, Py, Java. it works ok.

**Comment by veksha** [comment]
is ok to merge?

**Comment by Alexey-T** [comment]
yes, seems ok
