### ISSUE TITLE
HTML LSP: not correct sorting of autocompletion list when 'id' has '-'

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#120]
![ht-l](https://user-images.githubusercontent.com/4154978/202924112-858be02e-9183-4666-a55a-ba88bc0c7df0.png)

@veksha can be improved?

**Comment by Alexey-T** [comment]
`<table style="border-col|lapse:`

here is worse

![Screenshot from 2022-11-20 23-20-04](https://user-images.githubusercontent.com/4154978/202924285-749e1d2c-8eb3-4306-9705-0490d23a3454.png)

**Comment by veksha** [comment]
for some reason autocompletion stopped working for me inside style attr.

**Comment by veksha** [comment]
we must do something with `nonword_chars` setting for HTML lexer.

**Comment by veksha** [comment]
{
    "nonword_chars": "\""
}
![image](https://user-images.githubusercontent.com/275333/202927537-f6c27fe7-5adc-454b-b621-9a5b41396289.png)

**Comment by Alexey-T** [comment]
hm, why do you suggest to add dbl-quote to nonword_chars? not the dash?

**Comment by veksha** [comment]
minus "-" char must not be in nonword_chars for HTML I think. all others can stay?

**Comment by Alexey-T** [comment]
ah, okay. will add this to the wiki
