### ISSUE TITLE
Semantic Tokens support

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#121]
https://github.com/veksha/cuda_lsp/tree/SemanticTokens

@Alexey-T please test this branch. added support for [Semantic Tokens](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_semanticTokens)

lsp servers that support Semantic Tokens:
- c++ (clangd)
- Java
- Lua
- js, typescript
- markdown
- rust

**Comment by Alexey-T** [comment]
how can I activate this feature and see it?

**Comment by Alexey-T** [comment]
we need to be able to disable this. pls.

**Comment by veksha** [comment]
for now i paint only the following tokens, but can be added more.

```python
if t in ('class'):
    color_font=0xFF00
elif t in ('variable', 'parameter'):
    color_font=0x55AA
elif t in ('method', 'function'):
    color_font=0x5522AA
```

**Comment by Alexey-T** [comment]
how it is useful? IMO no use for me.

**Comment by veksha** [comment]
with lexer you cannot paint var , params, funcs, classes in different colors. they are all white.

**Comment by veksha** [comment]
also constants can be painted in distinct color form vars, etc...

**Comment by Alexey-T** [comment]
pls, only optional!

**Comment by veksha** [comment]
yes. and colors must be configurable?

Question: can we detect if current theme is dark or light?

**Comment by Alexey-T** [comment]
>can we detect if current theme is dark or light?

yes, by evristic, eg take max(r,g,b) for the color_of_text_bg and compare to 0x80

**Comment by Alexey-T** [comment]
>yes. and colors must be configurable?

yes, this feature needs N (>4) colors for each token  type. comma separated int values are needed

**Comment by Alexey-T** [comment]
Pls make all related LSP requests off, if feature is off

**Comment by veksha** [comment]
updated branch

**Comment by Alexey-T** [comment]
works OK. note: semantic highlight is meant for another purpose. to highliught different IDs in different colors. not - all IDs have the same color (IDs if the same kind).

**Comment by veksha** [comment]
> note: semantic highlight is meant for another purpose. to highliught different IDs in different colors. now - all IDs have the same color (IDs if the same kind).

Semantic Tokens according to LSP specification is providing information about ID's type(class/var/param/macro/etc..) and modifiers(global/static/readonly/etc..)
for example, you want all classes to be painted green, or all readonly vars be painted in teal color.

you mean something different by "semantic highlight".

**Comment by veksha** [comment]
here I paint all classes in green, macros in red, const vars/params in teal.
it was all gray before.

![image](https://user-images.githubusercontent.com/275333/203311384-5fa2edbe-088f-4130-ba15-72fdc5d1e1b2.png)

**Comment by Alexey-T** [comment]
also pls add the screenshotted C++ file to plugin, as readme/test_semantic_tokens.cpp .
