### ISSUE TITLE
C++ server with 'operator ='

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#124]
```
class Player
{
   Player();
   void func1();
   void func2();
   void func3();
   void func4();
};

Player::Player()
{
    
}
void Player::func1()
{
    
}
void Player::func2()
{
    
}
void Player::func3()
{
    
}
void Player::func4()
{
  Player::|
}
```
caret in last block. call autocompl, choose
![Screenshot from 2022-11-23 22-58-32](https://user-images.githubusercontent.com/4154978/203635816-8490b820-b4c1-44e1-8516-5536ed90acda.png)

->
`  Player::operator=()  `
its OK?

**Comment by veksha** [comment]
I don't know why clangd suggests `operator=()` method when there is no such method exists in a class.

but if you declare it, it compiles OK:
```c++
class Player
{
   Player();
   void func1();
   void operator=(Player &p);
};

Player::Player()
{
    
}

void Player::operator=(Player &p)
{
    
}

void Player::func1()
{
    Player p;
    Player::operator=(p);
}
int main() {}
```

**Comment by Alexey-T** [comment]
@veksha see my screenshot. 'Player' is constructor? why it is missing brackets? desctuctor is okay.
