### ISSUE TITLE
rust lsp doesnt seems to work

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [CudaText-addons/cuda_lsp#125]
the currently used config is >
{
  "lexers": {
    "Rust": "rust"
  },
  "cmd_windows": ["D:\\testlsp\\rust-analyzer-x86_64-pc-windows-msvc.exe"],
  "cmd_unix": ["rust-analyzer-x86_64-unknown-linux-gnu"]
}

it has the log but no effect>
LSP: starting server - Rust; root: None
Startup: 1530ms, plugins: 630ms (tabs_list 109ms, lsp 516ms)
Read channels:
  getting: plugins.json

**Comment by Alexey-T** [comment]
what OS?
show the log?

**Comment by veksha** [comment]
"root: None" how root can be none? try to save Cud's project file to your rust application project dir.

**Comment by Alexey-T** [comment]
I usually also see “root: None” and all works.

**Comment by veksha** [comment]
BTW, @Alexey-T, how can I reproduce “root: None” on Windows? it always has some value.

**Comment by Alexey-T** [comment]
Close the current project (in Project Man context menu), restart cud

**Comment by veksha** [comment]
`temporary.cuda-proj` will be opened with `cudatext\settings` as root

**Comment by Alexey-T** [comment]
Temporary project must not be reopened if you close last project, don’t pass dirs in cmd line

**Comment by veksha** [comment]
how to close last project? "new project"?

**Comment by Alexey-T** [comment]
Yes

**Comment by veksha** [comment]
> Temporary project must not be reopened if you close last project, don’t pass dirs in cmd line

then this is not working on Windows.

**Comment by Alexey-T** [comment]
Are you sure no dirs are passed in cmd line ? Try with clean app

**Comment by veksha** [comment]
only when i close ALL TABS and restart then it has no temporary project, but as soon as I reopen last file temporary project is opened too, but server will start with root: none. hm...
if you has some tabs opened and restart, you will see that server will start with root: "cudatext\settings"

**Comment by Alexey-T** [comment]
Did you clear the opt in Proj Man - on opening file in git/svn……. ?

**Comment by veksha** [comment]
no

**Comment by veksha** [comment]
cleared it now and I see that temporary proj is not reopening now. hm..

**Comment by veksha** [comment]
what is the default for - "on opening file in git/svn……. " option?

**Comment by Alexey-T** [comment]
On

**Comment by Alexey-T** [comment]
Do you mean it makes new project even w/o git file?

**Comment by veksha** [comment]
if you will have root: none, you will see "rust-analyzer failed to discover workspace" message and nothing will work.
for rust lsp to scan your file you must set correct root.

**Comment by veksha** [comment]
> Do you mean it makes new project even w/o git file?

no, i have .git folder. so I think it works correctly.
almost correctly. because after restart Proj manager will search for the git repo near the first file/tab opened in Cud, not the active file/tab.

**Comment by veksha** [comment]
> I usually also see “root: None” and all works.

for rust lsp too??

**Comment by veksha** [comment]
also we mus take into account this option in Cuda_lsp:
```
* root_dir_source - LSP server root directory source (accepts list of values for fallback):
    * 0 - parent directory of '.cuda-proj'
    * 1 - first directory in project
    * 2 - project main-file's directory
```

**Comment by veksha** [comment]
if we set `"root_dir_source": [1,0,2],` then rust lsp will be started with root dir set to first prject dir and all will be ok.

**Comment by veksha** [comment]
but if we "close tab" / "reopen tab" then root will still be "None".
all is complicated.

**Comment by Alexey-T** [comment]
Project man option works when no proj is opened yet; for other files it don’t have effect

**Comment by RESDXChgfore9hing** [comment]
so in short for rustlsp to work we must have a project root?in the rust_lsp.json?
"root_dir_source": "somepathwithrustsourcecode",

**Comment by Alexey-T** [comment]
no, LSP plugin makes the project root from Project Manager plugin active project. see LSP options file, you can change it.

**Comment by RESDXChgfore9hing** [comment]
project manager plugin?doesnt seems to have this?

**Comment by Alexey-T** [comment]
It is preinstalled.

**Comment by RESDXChgfore9hing** [comment]
i see i have no idea how to edit it.@@

**Comment by Alexey-T** [comment]
- create new project in Project Manager (call it in sidebar, add some folders, then save as)

**Comment by RESDXChgfore9hing** [comment]
something like this?
![correctmaybecudarustlspproj](https://user-images.githubusercontent.com/75789716/205102265-43efb121-475e-4867-88ba-49fb654d6a06.PNG)

**Comment by RESDXChgfore9hing** [comment]
it seems to have worked*(detecting the root folder)
but no real effects of the lsp working though
:Loading project: D:\testlsp\testrustlsp_proj\test1.cuda-proj
LSP: starting server - Rust; root: D:\testlsp\testrustlsp_proj
Startup: 1480ms, plugins: 910ms (lsp 391ms, project_man 516ms)

**Comment by veksha** [comment]
click on LSP icon on side bar and look for any messages there.
also if you are on Windows you must use double backslashes in config:

i see you have single backslashes:
 "cmd_windows": ["D:\testlsp\rust-analyzer-x86_64-pc-windows-msvc.exe"],

**Comment by RESDXChgfore9hing** [comment]
oh yea there is:rust-analyzer failed to discover workspace

**Comment by veksha** [comment]
now do internet search.
here one link which may be useful: https://stackoverflow.com/questions/72062935/rust-analyzer-failed-to-discover-workspace-in-vscode

**Comment by RESDXChgfore9hing** [comment]
conclusion: very not flexible,only useful for large projects,
need setup per project(see above,uncertain reproducibility).
closing this issue.
