### ISSUE TITLE
failed to properly use c/c++ lsp with clangd

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [CudaText-addons/cuda_lsp#126]
ERROR: error on loading json. Log file: D:\2ndProgramFiles\cudatext\settings\cudax.log
NOTE: LSP: server config error - no associated lexers: D:\2ndProgramFiles\cudatext\settings\lsp_c.json

It seems like it says there is no lexer
however i use the plugin manager typed :lexer c
i only see cuda c++,and dont see any other lexer?
So where is the lexer?to make it work?or is it my json fault?

lsp_c.json
____
{
  "lexers": {
    "C++": "cpp",
    "C": "c"
  },
  "cmd_unix": [
      "clangd-12",
  ],
  "cmd_windows": [
      "D:\testlsp\cpp\clangd_15.0.6\bin\clangd.exe"
  ],
}

**Comment by Alexey-T** [comment]
You have single \ slashes, but it must be double.

**Comment by RESDXChgfore9hing** [comment]
ohhh,it worked thanks oops.
