### ISSUE TITLE
cpu load after closing tab

### ISSUE THREAD

**Issue by ildarkhasanshin** [CudaText-addons/cuda_lsp#128]
процессор остается постоянно загруженным в районе 10-12% после закрытия вкладки
норм?

**Comment by Alexey-T** [comment]
@veksha
do you confirm?
even if we wait for 1-2 secs after closing 1 tab?

**Comment by ildarkhasanshin** [comment]
> even if we wait for 1-2 secs after closing 1 tab?

да

**Comment by veksha** [comment]
у меня 0%. @ildarkhasanshin  можешь скриншот окна сделать или видео записать? какие плагины используешь?

**Comment by ildarkhasanshin** [comment]
вроде как дело не в других плагинах

вот скринкаст с отключенным cuda_lsp и включенным

[file:///home/ildar/Видео/vokoscreenNG-2022-12-12_22-07-29.mkv](url)

конфиг cuda_lsp.json такой
```
{
  "root_dir_source": [
    0
  ],
  "send_change_on_request": false,
  "enable_mouse_hover": true,
  "hover_dlg_max_lines": 10,
  "hover_additional_commands": [
    "Definition",
    "References",
    "Implementation",
    "Declaration",
    "Type definition"
  ],
  "cudatext_in_py_env": false,
  "lint_type": "d",
  "lint_underline_style": 2,
  "enable_code_tree": false,
  "tree_types_show": "",
  "auto_append_bracket": true,
  "hard_filter": false,
  "use_cache": true
}
```

**Comment by veksha** [comment]
т.е. это только с PHP проблема? каковы настройки php lsp сервера? (lsp_php.json)
может сервер долго сканирует папку проекта (в ней много файлов)?
какие сообщения видны на панели lsp ?

**Comment by ildarkhasanshin** [comment]
> т.е. это только с PHP проблема?

нет, с py-файлами аналогично


> каковы настройки php lsp сервера? (lsp_php.json)
```
{
    "name": "PHP",
    "lexers": {
        "PHP": "php"
    },
    "tcp_port": 12345,
    "cmd_unix": [
      "php",
      "/home/ildar/.config/cudatext/lsp/php-language-server-main/bin/php-language-server.php",
      "--tcp-server=127.0.0.1:12345"
    ]
}
```

> может сервер долго сканирует папку проекта (в ней много файлов)?

один

> какие сообщения видны на панели lsp ?

```
OK!
0 files total
Indexing project for definitions and static references
Indexing project for dynamic references
0 Packages
All 0 PHP files parsed in 0 seconds. 188 MiB allocated.
```

**Comment by veksha** [comment]
у меня на виртуальной Ubuntu 2-3%
если двигать мышкой может доходить до 20-25%
на Windows практически всегда 0%

не знаю почему такое различие.
