### ISSUE TITLE
lsp_bash

### ISSUE THREAD

**Issue by eltonfabricio10** [CudaText-addons/cuda_lsp#134]
The cmd not replaced until at the beginning of the line

![Peek 11-01-2023 18-11](https://user-images.githubusercontent.com/25956396/211919266-5387f91f-1c07-4ed4-b6c8-46c5f2c9085f.gif)

Steps:
- type "xdg-op"
- choose cmd
- press tab-key

**Comment by veksha** [comment]
nonword_chars must include hyphen (minus) char?

**Comment by eltonfabricio10** [comment]
Oh! My mistake, sorry!
