### ISSUE TITLE
slowdown when in Python auto-completion auto-show is called in comment

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#137]
Caret is after comment char here, and I type text: 

![py](https://user-images.githubusercontent.com/4154978/228316987-fb9d0b4c-c142-458c-a385-1bd4c1a21270.png)

"autocomplete_autoshow_chars">0 calls LSP and I see big slowdown when I type text of comment and LSP is tryping to show something unneeded .. @veksha

maybe Client can detect the caret in comment and avoid the work?
```
ed.get_token()
```

**Comment by veksha** [comment]
i'm testing LSP autocompletion for TailwindCSS (HTML lexer).

```html
<div class="bg|">
</div>
```

`ctrl+space` is not working here because we disallowed it by this line:
```if self.ed.get_token(TOKEN_GET_KIND, x1, y1) in ('s','c'):      return```

I think we need new cuda_lsp option to enable/disable autocompletion in strings/comments.

**Comment by Alexey-T** [comment]
Yes, please add the option with str value, 

- if 'c' in value: disable autocompletion in syntax comments
- if 's' in value: disable autocompletion in syntax strings

**Comment by veksha** [comment]
interestingly enough, autocomple_autoshow_chars > 0 it works (not `ctrl+space`), because in that case get_token returns 'a' for some reason!

**Comment by Alexey-T** [comment]
I see repro in Console. will see it.

**Comment by Alexey-T** [comment]
No repro in Console for TOKEN_GET_KIND, it returns 's' for caret on last quite

![Screenshot from 2023-04-13 13-50-11](https://user-images.githubusercontent.com/4154978/231736985-bbc4bc57-6577-49f7-b3b2-24b76c11c168.png)

**Comment by veksha** [comment]
reproduces only when typing and auto-complete auto-show is activated.

**Comment by veksha** [comment]
https://user-images.githubusercontent.com/275333/231738131-7c26bdde-a559-4ffe-ba03-ec9be14eb248.mp4

**Comment by Alexey-T** [comment]
To repro I need Tailwind LSP server? I dont want to play with it.

formframe.pas
find the
```
          if EditorAutoCompletionAfterTypingChar(Ed, AText, FTextCharsTyped) then
```
and try to add `Sleep(time_in_msec)` before it.

**Comment by Alexey-T** [comment]
Or try to call python's sleep, it is the same,

**Comment by veksha** [comment]
also cached autocompletion results still showing despite context. (will fix)

**Comment by veksha** [comment]
> To repro I need Tailwind LSP server?

no. do you have lsp python server?

**Comment by Alexey-T** [comment]
yes, I do.

**Comment by veksha** [comment]
put `print(self.ed.get_token(TOKEN_GET_KIND, x1, y1))` line in `book.py` like on my video. then configure autocomplete_autoshow_chars, and type in "" somewhere in python file.

**Comment by veksha** [comment]
> formframe.pas find the
> 
> ```
>           if EditorAutoCompletionAfterTypingChar(Ed, AText, FTextCharsTyped) then
> ```
> 
> and try to add `Sleep(time_in_msec)` before it.

with `Application.ProcessMessages;` it works. (with `sleep` doesn't)

**Comment by Alexey-T** [comment]
this fix helps you?
book.py
```
    def get_docpos(self, caret=None):
        if caret is None: # caret pos
            x1, y1, _x2, _y2 = self.ed.get_carets()[0]
            # is in comment or string
            print('tok:', self.ed.get_token(TOKEN_GET_KIND, x1, y1))
            if self.ed.get_token(TOKEN_GET_KIND, x1, y1) in ('s','c'):
                sleep(0.1) # give some timer to lexer-parser in thread     
                if self.ed.get_token(TOKEN_GET_KIND, x1, y1) in ('s','c'):
                    return
        else:  # mouse pos
```

**Comment by Alexey-T** [comment]
what if you add sleep in book.py?
```
            sleep(0.1) # give some timer to lexer-parser in thread     
            if self.ed.get_token(TOKEN_GET_KIND, x1, y1) in ('s','c'):
                return
```

**Comment by veksha** [comment]
doesn't work. and all becomes slooow.

**Comment by Alexey-T** [comment]
better fix here: proc_editor.pas,
find
```
if ACharsTyped>=Ed.OptAutocompleteAutoshowCharCount then
```
add line in begin/end
```
    if ACharsTyped>=Ed.OptAutocompleteAutoshowCharCount then
    begin
      //ACharsTyped:= 0; //don't reset, fix #4479
      Application.ProcessMessages; //fix https://github.com/CudaText-addons/cuda_lsp/issues/137

      AppRunAutocomplete(Ed, true);
      exit;
    end; 
```

**Comment by veksha** [comment]
works here too.

**Comment by Alexey-T** [comment]
Applied.

**Comment by veksha** [comment]
> Yes, please add the option with str value,
> 
> * if 'c' in value: disable autocompletion in syntax comments
> * if 's' in value: disable autocompletion in syntax strings

> "disabled_contexts"

what is default value?

**Comment by Alexey-T** [comment]
disabled_contexts=cs

If it's possible, give the option per-server (in CSS server we need to allow strings, in Python - not)
