### ISSUE TITLE
insert C++ snippet 'while' - indents are little wrong

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#149]
I have current editor's tabs_as_spaces on, and tab_size==4.
but 'while' snippet gave indents== 2 spaces.

![c](https://user-images.githubusercontent.com/4154978/233368728-61e5aa2a-43d9-4cd2-a6f7-8c97ced6c523.png)

who is culprit? @veksha

i know that snippets must have tab-chars as their indents. so my snippet-code can replace tab-chars to ok number of spaces.

**Comment by veksha** [comment]
i see that it's depending on caret x pos.
i htink these snippets contain no indent at all.
must be:

```
while (condition) {
statements
}

```

**Comment by veksha** [comment]
i need to offset x pos.

**Comment by veksha** [comment]
fixed. nice catch!
