### ISSUE TITLE
multiple servers for one lexer

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#151]
branch: https://github.com/veksha/cuda_lsp/tree/multiple_servers

tested with servers: html + tailwind css

https://user-images.githubusercontent.com/275333/233383640-76bfeb14-94e6-428b-97cb-a288544a53a1.mp4

**Comment by Alexey-T** [comment]
Btw, could you delete old git branches, pls?

**Comment by veksha** [comment]
another cases:
- pylsp + pyright
- any lsp server + CompleteFromText

but this is not supported now, because I don't know how to mix autocompletion results in one listbox, and how to mix CompleteFormText data with lsp listbox.

**Comment by veksha** [comment]
> Btw, could you delete old git branches, pls?

done.

**Comment by Alexey-T** [comment]
I don’t understand the video. Instead , if n servers are supported, write about it to readme. I just need two ok configs? Nothing more? How to switch the active server?

**Comment by veksha** [comment]
in **main** branch: for `HTML` files we can either use `html server` or `tailwind css server`. not both. code supports only 1. and only 1 will be started.
in **multiple_servers** branch: we can load and use them together. they will work with same file/tab/lexer.

> How to switch the active server?
in main branch: only one can be active. to switch between them - rename config files, restart Cud.
in my branch: any number of server can be active at the same time. it's up to user to make this decision, because right now good combination is html+tailwind, they don't interfere with each other.

**Comment by veksha** [comment]
(PS: tailwind css server - is for .html files, not .css)

**Comment by Alexey-T** [comment]
I see now. I also understand the video now (before I used the smartphone).

**Comment by veksha** [comment]
> * any lsp server + CompleteFromText

if we somehow can mix results from those, it would be nice.

**Comment by Alexey-T** [comment]
we cannot yet. Plugin does not expose its results, it gets results and calls the `ed.complete` with them.

**Comment by Alexey-T** [comment]
let's merge multi-servers branch?

**Comment by veksha** [comment]
let's wait some time. it's not solid yet.
i already see some bugs in:
```
goto definition
goto references
```

**Comment by veksha** [comment]
> i already see some bugs in:
> 
> ```
> goto definition
> goto references
> ```

no. they work fine. I just added some lines to the top of the target file without saving, so LSP server didn't see those changes (it can't see until i save a file) and goto commands worked with old offset. this is ok.

**Comment by Alexey-T** [comment]
Which server will handle the pop up window on ctrl+mouseMove?

**Comment by Alexey-T** [comment]
The idea looks fragile…

**Comment by veksha** [comment]
we need to check how its done in other popular editors.

**Comment by veksha** [comment]
the only thing right now that is working correctly is when you configure two servers that will not interfere with each other:
-  html autocompletion works outside of strings, tailwind works inside strings.

**Comment by Alexey-T** [comment]
>A server should not operate with "multiple clients using RPC" at the same time. The protocol specifically states "[t]he protocol currently assumes that one server serves one tool." 

https://stackoverflow.com/questions/64000616/creating-lsp-language-server-protocol-for-multiple-clients-using-rpc

**Comment by veksha** [comment]
combination like pylsp + pyright is bad, because two autocompletion will pop up twice, hover too, etc...

**Comment by Alexey-T** [comment]
So it is not ok idea, only 2 html servers works good.

**Comment by veksha** [comment]
it must not break anything for users that will have only 1 server for 1 file.
so this branch is just a way to combine servers, if you know what you are doing.

**Comment by veksha** [comment]
closing for now. code to support multiple servers looks very ugly. need to think of different approach.
