### ISSUE TITLE
add option to reuse Complete From Text?

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#152]
@veksha I changed the CompFromTxt plugin. it now gives public API `get_completions(ed_self, x0, y0)`. you can call it (by option) from LSP. 

like this
```
try:
  import cuda_complete_from_text
except ImportError:
  cuda_complete_from_text = None

....

if cuda_complete_from_text is not None:
  more_completions = cuda_complete_from_text.get_completions(ed_self, x, y)
```

**Comment by Alexey-T** [comment]
Added 2 params to new API func: x0, y0

**Comment by Alexey-T** [comment]
Added more params to API. pls see the src of plugin.

**Comment by veksha** [comment]
added this, otherwise line `if not is_lexer_allowed(lex): return` is blocking.

```diff
diff --git a/__init__.py b/__init__.py
index 4358b3f..9fe4fcf 100644
--- a/__init__.py
+++ b/__init__.py
@@ -227,11 +227,11 @@ def get_acp_words(ed, word1, word2):
     return acp_words, words
 
 
-def get_completions(ed_self, x0, y0, with_acp):
+def get_completions(ed_self, x0, y0, with_acp, ignore_lexer=False):
 
     lex = ed_self.get_prop(PROP_LEXER_FILE, '')
     if lex is None: return
-    if not is_lexer_allowed(lex): return
+    if not ignore_lexer and not is_lexer_allowed(lex): return
 
     global nonwords
     nonwords = appx.get_opt(

```

**Comment by Alexey-T** [comment]
applied, thanks.

**Comment by Alexey-T** [comment]
LSP needs higher priority than ComplFromText, yes? You can make it high via install.inf, see API wiki “events priority”.

**Comment by veksha** [comment]
btw, found bug. tab name can contain "|" char. but this char also used as delimiter in CompleteFromText.
maybe choose different char?

**Comment by Alexey-T** [comment]
Api of Cud don’t allow to change this char, so I will replace this char in tab title to eg dash
