### ISSUE TITLE
space-indent for results; but CompFromText lines don't have this indent

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#155]
![Screenshot from 2023-04-21 00-02-22](https://user-images.githubusercontent.com/4154978/233487301-d21de107-d0f0-4b17-a867-e0ef24b47edc.png)

**Comment by veksha** [comment]
do you mean spaces between `prove` and `(test.c)` ?

**Comment by Alexey-T** [comment]
no, leading space before text

**Comment by veksha** [comment]
leading space is coming from clangd for clangd results only. because they use "🞄" char in place of space for snippets.

**Comment by veksha** [comment]
well, not for snippets, but for completions with edits (which adds `#include` at top of file automatically)

**Comment by veksha** [comment]
![image](https://user-images.githubusercontent.com/275333/233491096-23f73218-04a6-497a-b837-7c2a176aa302.png)

**Comment by Alexey-T** [comment]
ok
