### ISSUE TITLE
`autocomplete_autoshow_chars: 2`, typing inside python string - no autocompletion

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#156]
but ctrl+space works.

repro:
file `language.py`, line: `print(f'NOTE: {LOG_NAME}: odd item: {item}')`
delete "item" and start typing text: "it"

(in lsp config `"disabled_contexts": ""` empty)

**Comment by Alexey-T** [comment]
Seems Cud is ok, because single place of tokens-check is here
```
procedure TfmMain.DoAutoComplete(Ed: TATSynEdit);
...
  //disable completion in comments/strings
  if DoAutoComplete_PosOnBadToken(Ed, Caret.PosX, Caret.PosY) then exit;
```
it's for both ctrl+space and autoshow.

**Comment by veksha** [comment]
see, ctrl+space works:

https://user-images.githubusercontent.com/275333/233491582-214a1420-dbcd-45cc-b31f-124ade359147.mp4

**Comment by Alexey-T** [comment]
found the culprit, proc_editor.pas
```
  //autoshow by trigger chars
  if (Ed.OptAutocompleteTriggerChars<>'') and
    (Pos(AText[1], Ed.OptAutocompleteTriggerChars)>0) then
  begin
    //check that we are not inside comment/string
    if EditorCaretInsideCommentOrString(Ed, Caret.PosX, Caret.PosY) then exit;

    ACharsTyped:= 0;
    AppRunAutocomplete(Ed, true);
    exit;
  end;
```

**Comment by veksha** [comment]
it works in .json. strange.

https://user-images.githubusercontent.com/275333/233492266-0b77825e-08e4-4a7a-9063-2a4a2d4b6e74.mp4

**Comment by Alexey-T** [comment]
try my Cud patch.

**Comment by veksha** [comment]
works. thanks!

**Comment by veksha** [comment]
maybe related to this issue:

typing "e2" - autoshow works.
typing "2c" - doesn't work.

https://user-images.githubusercontent.com/275333/233604758-a01c2be8-db05-432b-936b-58943abbba5f.mp4

**Comment by veksha** [comment]
`language.py` 1923 line

**Comment by Alexey-T** [comment]
Cud
proc_editor.pas
```
  //autoshow for all, when typed N chars
  if (Ed.OptAutocompleteAutoshowCharCount>0) then
  begin
    //ignore if number typed
    bIdentChar:= bWordChar and not IsCharDigit(AText[1]);
    if (ACharsTyped=0) and (not bIdentChar) then exit;
         
```
so it's on purpose.

**Comment by veksha** [comment]
i see. but, can we remove this check?

**Comment by veksha** [comment]
another tiny issue: for html files, `autocomplete_html` option if enabled negates `autocomplete_autoshow_chars: 2`.
in other words: `autocomplete_html: true` makes `autocomplete_autoshow_chars: 1` even if i set 2.

**Comment by Alexey-T** [comment]
> i see. but, can we remove this check?

no, because it disables autoshow when we type a number. code don't check the previous char - it checks only first typed char.

**Comment by Alexey-T** [comment]
>another tiny issue: for html files

please, make new issue of Cud.
