### ISSUE TITLE
lexer Markdown in the hover-window looks wrong

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#162]
MD lexer handles `_` and `*`. It is bad here.

![Screenshot from 2023-04-24 22-31-19](https://user-images.githubusercontent.com/4154978/234097387-b67791e2-6c52-46ee-b15b-be7d92fe87ff.png)

**Comment by Alexey-T** [comment]
@veksha, what do you think , maybe don’t use lexer in this dialog is better?

**Comment by veksha** [comment]
what lsp server do you use?

pyright:

![cudatext_M1iLRl96Ot](https://github.com/CudaText-addons/cuda_lsp/assets/275333/effaff75-85ba-414b-aebb-24eb177e7c45)

pylsp:

![cudatext_iJbbLVtRBg](https://github.com/CudaText-addons/cuda_lsp/assets/275333/d3e320ae-352f-4a80-b55d-6e885cc36254)

**Comment by veksha** [comment]
this can be bug of lsp server. check same server in sublime or vscode.
