### ISSUE TITLE
CompleteFromText results have unneeded popups

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#163]
@veksha , is it bug of plugin? Of Cud (if so, can you give small repro in console)?
https://github.com/Alexey-T/CudaText/issues/5018#issuecomment-1520673689

**Comment by veksha** [comment]
cuda_lsp uses only `Editor.complete_alt` API. it has no popups, AFAIK.
`Complete From Text` addon uses `Editor.complete` API, which has tooltips.

**Comment by veksha** [comment]
in Console try:
`ed.complete('text|text2\ttext3\ntext4',0,0)`

**Comment by Alexey-T** [comment]
@d0vgan
seems fixed after my patch to 'atsynedit_cmp'. but veksha's Console example fails to show hint now....

**Comment by Alexey-T** [comment]
Fixed it now.
