### ISSUE TITLE
lsp server does not start after restarting Cud (1st tab: "Untitled1" with text, 2nd tab: "Language.py" modified)

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#164]
1st tab must be "Untitled1" with text
2nd tab: for example "Language.py" but **MODIFIED**

activate 2nd tab ("Language.py") before restarting.

**Comment by Alexey-T** [comment]
Cud should fire on_open when you activate 2nd tab after start.

**Comment by Alexey-T** [comment]
on_open : I forgot when it fires for passive tab, on app start or on tab-activating, you need to put 'print' and check.

in on_open, how LSP reads the file, using ed.get_text_all? then it must get OK lines even for modified tab

**Comment by veksha** [comment]
i see a problem.
`on_tab_change` event is coming at startup for 2nd tab ONLY when it is not modified.
can it be fixed?
