### ISSUE TITLE
CLang server don't insert snippet params

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#166]
![Screenshot from 2023-04-25 21-03-26](https://user-images.githubusercontent.com/4154978/234363558-907bd1f4-cef0-4329-9f41-27b1d31f4a20.png)

no bullet near `static_assert` but I see 'snippet' on it.

no inserted 2 params of this snippet. it inserts only 1 word.

```
user@PC:~$ clangd-12 --version
Ubuntu clangd version 12.0.0-3ubuntu1~20.04.5
```

**Comment by Alexey-T** [comment]
CLang issue. not plugin issue.

**Comment by veksha** [comment]
> no bullet near `static_assert` but I see 'snippet' on it.

bullets are for items with "edits" (edits can insert "#include <header>", etc...)

**Comment by veksha** [comment]
as for `static_assert`,
i have to look, maybe i remove simple params.. of simple snippets.

**Comment by veksha** [comment]
this snippet is `static_assert(${1:expression}, ${0:message});`
params like this must be preserved, i think.

**Comment by Alexey-T** [comment]
but these params are not inserted!

**Comment by veksha** [comment]
fixed in PR
