### ISSUE TITLE
first LSP call: no special 'bullet' items; next call: more items

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#168]
```
enum eState { stateOn, stateOff };
st
```

- caret after 'st' on line 2
- Cud just opened, cpp file just opened
- no 'bullet' items in LSP listbox
- now I type "a" after "st" and bullet items appear!
 
clangd version 16 , latest from github.

**Comment by Alexey-T** [comment]
[Kazam_00001.webm](https://user-images.githubusercontent.com/4154978/234368051-3afe8095-117e-42c5-a893-938571ec8410.webm)

**Comment by veksha** [comment]
it's not the first .cpp file you open after you launched CudaText?
restart Cud and open only this file and try again. (will be less results)

clangd will suggest more results when you open other file (in other tab) with `#include <...>` lines (or when you add it manually into current file)

**Comment by Alexey-T** [comment]
>it's not the first .cpp file you open after you launched CudaText?

first one.

**Comment by Alexey-T** [comment]
if I wait 20-30 secs, then all is ok. server initing!
