### ISSUE TITLE
Clangd item with <> brackets

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#172]
Is it parsed ok?  i see black font, not gray.

![Screenshot from 2023-04-26 00-22-31](https://user-images.githubusercontent.com/4154978/234407269-9eeba359-896f-46c4-b058-23d0d49780f0.png)

**Comment by Alexey-T** [comment]
More items with < >

![Screenshot from 2023-04-26 00-25-15](https://user-images.githubusercontent.com/4154978/234407592-c3872faf-5786-4b83-9986-0ced16eb9902.png)

**Comment by veksha** [comment]
parsing takes into account only "(" and ")" chars.

**Comment by Alexey-T** [comment]
okay
