### ISSUE TITLE
abuout python env problems

### ISSUE THREAD

**Issue by Adesince** [CudaText-addons/cuda_lsp#176]
This plugin helps me to write python scripts,thanks. But I meet some problem about config lsp_pyright.I use the anaconda virtual env in anaconda3/envs/pytorch/python.exe for my project, but the pyright can't use this env .Such as "import torch",I can run this ,but pyright say it can't find this moudle.
![image](https://user-images.githubusercontent.com/56526517/234770355-cde1dd7c-2208-4c95-a5d8-6611b3fcb8e1.png)
and follow is my lsp_pyright.json
![image](https://user-images.githubusercontent.com/56526517/234770620-565ecf6e-369e-40f1-996d-9e509c558101.png)
I'm a rookie in programing and my english is poor.Excuse me

**Comment by Adesince** [comment]
I think it maybe useful if I can run comand "conda activate pytorch" before the"pyright-langserver --stdio" .But I try "cmd_windows":["conda activate pytorch","pyright-langserver","--stdio"], it doesn't work

**Comment by veksha** [comment]
hi, @Adesince .
what if you try `"cmd_windows": ["pyright-langserver.exe", "-v" , "G:/anaconda3/envs/pytorch", "--stdio"],`

**Comment by Adesince** [comment]
I try it and I create a file name "pyrightconfig.json" according the pright dom,
![image](https://user-images.githubusercontent.com/56526517/234837297-975c8f89-f348-479b-8803-7d42ec46f01b.png)
![image](https://user-images.githubusercontent.com/56526517/234837354-b127177b-cabf-4be2-bff7-47b77864183e.png)
![image](https://user-images.githubusercontent.com/56526517/234837657-65612110-77d6-4514-96a6-d3280c8d6666.png)
But it still doesn't work. I'm sure the path is right, because I can run this code.

**Comment by veksha** [comment]
Where is you CudaText project file saved?

**Comment by Adesince** [comment]
I make a test project
![image](https://user-images.githubusercontent.com/56526517/234840402-b9e17b21-02b9-4d7b-8009-d2516be8365d.png)
and the cudatext project file in:
![image](https://user-images.githubusercontent.com/56526517/234840736-1363bf5c-23cc-41d1-85c5-eb0e7c2a8e5b.png)

**Comment by Adesince** [comment]
And my anaconda env  path is 
![image](https://user-images.githubusercontent.com/56526517/234841186-13c1c365-2845-4ed3-81dc-0fa49c2cc970.png)
I don't know why it doesn't work :(

**Comment by veksha** [comment]
this worked for me in pyrightconfig.json:

```json
{
  "stubPath": "G:/anaconda3/envs/pytorch/lib/site-packages"
}
```

**Comment by veksha** [comment]
![image](https://user-images.githubusercontent.com/275333/234845516-549d7e3b-429d-4efc-ac1a-68901d23d436.png)

**Comment by veksha** [comment]
1. save `.cuda-proj` to dir where `pyrightconfig.json` is located
2. configure `stubPath` in `pyrightconfig.json`
3. restart CudaText

**Comment by Adesince** [comment]
I save the .cuda-proj in the project dir, it still doesn't work. Then I try to add the "stubPath" as you sat , amazingly It worked. I think I should read the pyright document carefully, I even don't konw the option "stubPath" . It works, thank you very much.😊😊

**Comment by veksha** [comment]
answer about `stubPath` was found here: https://github.com/emacs-lsp/lsp-pyright/issues/7
i don't know if this is correct approach, but it works.

**Comment by veksha** [comment]
also check lsp log in bottom panel.
maybe python version is wrong still.

3.8 is global
3.10 in anaconda env

i see it assumes 3.8:

![image](https://user-images.githubusercontent.com/275333/234847213-0536043e-1d1f-4867-bfe8-b0f71ec27b62.png)

**Comment by Adesince** [comment]
It seems that  the python 3.8 is cudatext's python environment. Because my global python version is 3.9.13, and my conda env version is 3.9.16. So I don,t know why lsp_server can't use the virtual python environment

**Comment by Adesince** [comment]
But I set the project python version is "3.9.16" in pyrightconfig.json, and the python path to excute the python script also is my conda env, so I think it isn't a problem mybe.
