### ISSUE TITLE
v-analyzer (new V lang lsp server)

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#186]
https://github.com/v-analyzer/v-analyzer

old server (VLS) is discontinued in favor of v-analyzer.

wiki can be updated to the following text:

LSP server for V
Install V lexer (from "Addons Manager / Plugins / Install")
Install V language
Install v-analyzer binary from https://github.com/v-analyzer/v-analyzer to a folder (that is included in PATH).
Create "lsp_v.json" in CudaText's "settings" folder with the following content:
{
  "lexers": {
    "V": "v"
  },
  "cmd_windows": ["v-analyzer.exe"],
  "cmd_unix": ["v-analyzer"],
  "cmd_macos": ["v-analyzer"]
}

**Comment by Alexey-T** [comment]
thanks for this information! wiki updated-- https://wiki.freepascal.org/CudaText_plugins#LSP_server_for_V
