### ISSUE TITLE
hint is too wide, out of the entire monitor - please wrap it

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#25]
@veksha

![Screenshot from 2022-09-20 13-09-50](https://user-images.githubusercontent.com/4154978/191232173-74892203-4759-4b17-9bba-03efdb2b7c24.png)

**Comment by veksha** [comment]
https://github.com/veksha/cuda_lsp/tree/hint_wrap
@Alexey-T, please, test this branch.

you will notice resize flicker sometimes. can't get rid of it.
if only I could get correct wrap_info **before** paint events of form/memo..
or somehow call paint event of form/memo on invisible canvas, to calculate all info before showing form.

**Comment by Alexey-T** [comment]
Did you try

- Ed.cmd(cCommand_RepaintEditor)
- Ed.action(EDACTION_REPAINT)

**Comment by Alexey-T** [comment]
new branch: on 1st call of hint for 'menu_proc',

![se](https://user-images.githubusercontent.com/4154978/193611409-63d8faec-bbfd-4723-99eb-aac3763667c2.png)

**Comment by veksha** [comment]
can't reproduce on windows, will try on linux.

**Comment by Alexey-T** [comment]
On all next calls, hint size is ok. Must be first call in CudaText session

**Comment by Alexey-T** [comment]
Idea - use canvas_proc to calc line width on pixels. Then calc how many parts you will have after wrapping . Wrapping can be soft wrap or hard wrap (insert Eol)

**Comment by veksha** [comment]
> Then calc how many parts you will have after wrapping

editor is word-wrapping by **word** not by **pixel**, so i can't correctly calculate number of wrapped lines with a simple dividing line-width by screen-width.

I can use this canvas to get line width (it will be better then using PROP_CELL_SIZE, because PROP_CELL_SIZE works only for monospaced font)
but for number of wrapped lines I need to use wrap_info. just need to think how to show window "behind the screen" and then get wrap_info and then "move to screen".

**Comment by Alexey-T** [comment]
e.g. you got pixel width = 1200 for line.
then remove last line's char and recalculate pixels width. e.g. its now 1180. still big? remove again last char.....

**Comment by veksha** [comment]
word-wrap is working on words. not on chars.

**Comment by Alexey-T** [comment]
yes. then, deletes not trailing char, but traling word, ie the logic is almost the same but delete bigger parts at end

**Comment by veksha** [comment]
@Alexey-T, please test this branch:
https://github.com/veksha/cuda_lsp/tree/hint_wrap_2

**Comment by Alexey-T** [comment]
no no, not wrapped at all (1st monitor is right, 2nd left)

![Screenshot from 2022-10-15 08-17-41](https://user-images.githubusercontent.com/4154978/195970182-139c1025-6ede-417e-89d5-47e3841e779e.png)

**Comment by Alexey-T** [comment]
but wrapped when window on the left mon! with big indent!

![Screenshot from 2022-10-15 08-19-04](https://user-images.githubusercontent.com/4154978/195970217-7a2bea7e-7dca-4de5-bfd7-1d4ec379cc06.png)

**Comment by Alexey-T** [comment]
but wrapped when window is on the left mon. with indent!


![Screenshot from 2022-10-15 08-19-58](https://user-images.githubusercontent.com/4154978/195970254-b7e17e0f-0e99-4e10-a733-e3eb539b66e4.png)

**Comment by veksha** [comment]
hey, @Alexey-T.

second monitor has the following values:
app_proc(PROC_COORD_MONITOR,0) (-1920, 0, 0, 1080)
app_proc(PROC_COORD_DESKTOP,0) (-1920, 0, 1920, 1080)

i'm not using PROC_COORD_DESKTOP. I use PROC_COORD_MONITOR to get size of desktop on current monitor.
I thought it would give standard positive values, but it gives -1920... etc..

how can I get current monitor resolution(size) ?

**Comment by veksha** [comment]
given x1,y1,x2,y2 = (-1920, 0, 0, 1080)
shoud I use simple math:
res_x = x2-x1
res_y = y2-y1

yes?
I have only two monitors. can't test with three.

**Comment by Alexey-T** [comment]
> to get size of desktop on current monitor.

hm? 'desktop' is, by defintion, combined area of all monitors. with 2 monitors desktop will be 2x wider. with 3 mon's - desktop may be 3x wider or 2x wider and 2x taller.

**Comment by Alexey-T** [comment]
>how can I get current monitor resolution(size) ?

PROC_COORD_MONITOR: Returns coords of monitor with app window. it is area of one of monitors 0...3.

**Comment by Alexey-T** [comment]
>shoud I use simple math:
res_x = x2-x1
res_y = y2-y1
yes?

yes

**Comment by Alexey-T** [comment]
Improved wiki
https://wiki.freepascal.org/CudaText_API#app_proc_-_Screen_coordinates

**Comment by veksha** [comment]
https://github.com/veksha/cuda_lsp/tree/hint_wrap_2

pushed changes. try it.

**Comment by veksha** [comment]
> with indent 50 px

indent is ok. i get overall width by calculating length of longest wrapped line.
since wrapping occurs by words (not by pixel or chars) you will see some small indent. it's ok.

**Comment by veksha** [comment]
A question for you:
how to **force** monospaced font for hint?

**Comment by Alexey-T** [comment]
PROP_FONT: 2-tuple (str, int): normal font: name, size.

**Comment by Alexey-T** [comment]
>pushed changes. try it.

works good! Tks.

**Comment by veksha** [comment]
> PROP_FONT: 2-tuple (str, int): normal font: name, size.

what value should I pass ? 'mono'? :)

**Comment by Alexey-T** [comment]
```
  AppDefaultEdFonts: array[0..2] of string =
    {$ifdef windows}
    ('Consolas', 'Courier New', 'Courier');
    {$else}
      {$ifdef darwin}
      ('Monaco', 'Liberation Mono', 'DejaVu Sans Mono');
      {$else}
        {$ifdef haiku}
        ('Noto Sans Mono', '', '');
        {$else}
        ('DejaVu Sans Mono', 'Liberation Mono', 'Courier New');
        {$endif}
      {$endif}
    {$endif}
```

**Comment by Alexey-T** [comment]
app_proc - System
PROC_ENUM_FONTS: Returns list of font names, currently installed in OS. Note: only few names are common in all OSes (like Arial, Courier, Courier New, maybe more).

it allows to list all available font names!

**Comment by veksha** [comment]
how to set default? empty str?

**Comment by Alexey-T** [comment]
special fontname 'default' is UI font name - but there is NO such special name for mono.

**Comment by veksha** [comment]
can be closed
