### ISSUE TITLE
branch 'SnippetSupport' bug on inserting inside a word

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#28]
new.cpp, clangd-12.

`te|st;`
autocomplete, choose 'tempnam' =>
`    tempnam(const char *__dir, const char *__pfx)st;`

`st ` at end!
@veksha

**Comment by Alexey-T** [comment]
`t|est;` . autocomplete, choose 'true' ->
`trueest;`

**Comment by veksha** [comment]
this is not a bug.
lsp server tells us caret positions which must be used to replace old text with new text.
we can obey this information (current implementation, (like in Sublime Text))
or we can discard this information and "be smarter" then lsp-server and replace old text using our own method (i.e. detect word under caret)

**Comment by Alexey-T** [comment]
ok

**Comment by veksha** [comment]
if it will be annoying, we can change it at any time.
