### ISSUE TITLE
clangd: calling completion in untitled document gives strage err

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#31]
@veksha, is it intended?

![Screenshot from 2022-09-20 23-05-04](https://user-images.githubusercontent.com/4154978/191354258-5815ae50-4828-4b91-b890-6300c67fd7d9.png)

**Comment by veksha** [comment]
how to reproduce?

i noticed strange bugs when you use clangd autocomplete on empty file (so there is no "{}" brackets)

**Comment by veksha** [comment]
![image](https://user-images.githubusercontent.com/275333/191356778-fef8a1f0-8bd5-433c-90f2-b6324ea6ed46.png)

**Comment by Alexey-T** [comment]
- empty document
- type "pr"
- ctrl+space

**Comment by veksha** [comment]
on windows all ok:
![image](https://user-images.githubusercontent.com/275333/191357352-86ff448d-b548-4459-8b06-91977edce13c.png)

**Comment by veksha** [comment]
try to complete this:
1. `{ pr }`

2. or this:
```
{
pr }
```

first case is bugged.

**Comment by veksha** [comment]
this is `snippet.py` issues.

**Comment by veksha** [comment]
`responseError`: can't reproduce. what is your project path?

**Comment by Alexey-T** [comment]
your issue is different - move to a new issue please.

my issue - don't save the file 'new.cpp'! just untitled doc with chosed lexer C++!

**Comment by veksha** [comment]
reproduced.

**Comment by veksha** [comment]
file path for new tabs: `untitled://*Untitled1`
we can detect this in cuda_lsp and repalce it with `file://`
or change it in Cud?

**Comment by Alexey-T** [comment]
no, file path in Cud is different , try in console:

ed.get_filename()

**Comment by veksha** [comment]
yes. i see in `utils.py` interesting code:
```python
def ed_uri(ed):
    fn = ed.get_filename()
    if fn:
        #return 'file://'+ed.get_filename()
        return path_to_uri(fn)
    else:
        return 'untitled://'+ed.get_prop(ct.PROP_TAB_TITLE)
```

**Comment by veksha** [comment]
changed `else` clause to this:
```python
else:
        return 'file:///'+ed.get_prop(ct.PROP_TAB_TITLE)
```

and now it works. please try this on your Linux.

**Comment by Alexey-T** [comment]
ok, thanks.

**Comment by veksha** [comment]
maybe it's not `snippet.py` bug, it can be `cuda_lsp` bug.
lsp-server can also bring so-called "additional edits" along with snippet. it might be them.

**Comment by Alexey-T** [comment]
okay..
