### ISSUE TITLE
(maybe) `additionalTextEdits` bug

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#32]
lexer: C++
server: clangd

EDIT: it reproduces only after you write `#include<stdio.h>`, then save, then delete all text. (clangd will then show more autocompletion results, even when all text will be deleted)

1. empty document! (no text at all)
2. type "E" and press `ctrl+space`
3. select `•EOF` for example. OR any other item with "•" (dot/bullet)
4. you will see that include statement is in correct position but caret is not!

![image](https://user-images.githubusercontent.com/275333/191366374-6c3adeba-11fe-4fe6-84df-aec847c0d13a.png)

1. now delete all text
2. press `ctrl+space`
3. scroll to `•EOF` then select it. (OR any other item with "•" (dot/bullet), for example `•NULL`)
4. you will see that caret is in correct position, but include statement is inserted in the wrong place!

![image](https://user-images.githubusercontent.com/275333/191366790-a16fc553-d1cd-4db7-aaee-69eba334d1a2.png)

**Comment by Alexey-T** [comment]
@veksha is bug still here?

**Comment by veksha** [comment]
no. all good.
