### ISSUE TITLE
bash-language-server error

### ISSUE THREAD

**Issue by eltonfabricio10** [CudaText-addons/cuda_lsp#33]
![Screenshot_20220920_223428](https://user-images.githubusercontent.com/25956396/191395102-1bb286ab-444c-4b3d-aedd-14b60a5d1f2d.png)

**Comment by eltonfabricio10** [comment]
I can't reproduce again, sorry.

**Comment by veksha** [comment]
happened to me too after I edit file, then select/remove all text and press ctrl+space. (I don't remember exact steps)
Cud thinks that some text is still selected, while I have no text at all in editor.

I don't know exact steps to reproduce.

**Comment by eltonfabricio10** [comment]
Steps:
- Create new file sh
- Type `case` and press tab key (Snippet)

**Comment by veksha** [comment]
this error 100% appears when you have a selection and you press ctrl+space. but sometimes Cud thinks that there is a selection, when there is not.
@eltonfabricio10 , I have no snippet named "case", can you share its contents?

**Comment by eltonfabricio10** [comment]
![Peek 20-09-2022 23-02](https://user-images.githubusercontent.com/25956396/191397650-5ce191aa-688f-4c74-91a9-ddddadc97267.gif)

**Comment by eltonfabricio10** [comment]
![Screenshot_20220920_230748](https://user-images.githubusercontent.com/25956396/191398290-c55248ca-e87a-4822-8db1-756d1c2debf6.png)

**Comment by veksha** [comment]
now i see.
you HAVE a selection and autocomplete triggers automatically after snippet has been inserted.

I think the solution is just to silence the error.

**Comment by veksha** [comment]
it's still not 100% reproducing for me.

**Comment by veksha** [comment]
@Alexey-T,
we can make this exception more friendly by adding try/except statements like this:

![image](https://user-images.githubusercontent.com/275333/191401344-2939cc17-b40c-483e-a787-d3b671c66e42.png)

**Comment by eltonfabricio10** [comment]
> it's still not 100% reproducing for me. EDIT: because this assert check is executing only when there is non-empty response from lsp-server.

[shellcheck,Wrn:2194]: SC2194: This word is constant. Did you forget the $ on a variable?

**Comment by eltonfabricio10** [comment]
Very strange that!
The error only appears with snippet: "case"

**Comment by Alexey-T** [comment]
yes, better silience the error.
