### ISSUE TITLE
Add the labels: Info and Warnings

### ISSUE THREAD

**Issue by eltonfabricio10** [CudaText-addons/cuda_lsp#36]
![Screenshot_20220924_210741](https://user-images.githubusercontent.com/25956396/192123314-85f8e269-a1e4-4a57-8c0e-2e7398121f14.png)

It's possible?

**Comment by veksha** [comment]
The guy who designed this (@halfbrained) is no longer on github, i think.
Maybe @Alexey-T can help.

Or I can help, but.. I'm not sure I understand your question, @eltonfabricio10.

I see these icons to toggle warnings/errors/etc..:
![image](https://user-images.githubusercontent.com/275333/192124546-b78ca8bc-44c2-45f1-b2c0-a122fc1270f7.png)

**Comment by eltonfabricio10** [comment]
I have an idea:
Move icons to the left and add labels to the side.

And remove those labels that are already on the right.

**Comment by Alexey-T** [comment]
my opinion: it works already (via icons on the right, yes).

**Comment by eltonfabricio10** [comment]
It's true, let's not waste time.
