### ISSUE TITLE
app.dlg_proc needs bracket

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#37]
plugin Comments src.
I type: `app.dlg_`, choose 'dlg_proc' -> no bracket added after 'app.dlg_proc' . 
@veksha
branch autocomplete.cache.2.

**Comment by veksha** [comment]
it works like in Sublime,
but I will try to do smart check/insertion of "()"

**Comment by Alexey-T** [comment]
by option "auto_append_bracket":true.

**Comment by veksha** [comment]
branch `autocomplete.cache.2`
new:
- auto_append_bracket option
- smart brackets
- refactoring

**Comment by Alexey-T** [comment]
works good!
only new option in missed in helper options_descriptions.md file.

**Comment by veksha** [comment]
added:
_* auto_append_bracket - after selecting a method in code completion listbox try to append parentheses automatically if they are missing_

PS:
`autocomplete.cache.2` branch needs a bit more refactoring of cache code (to make it more "human-readable"). but other then that it is ready for testing. please report any errors.

for `Bash` lexer brackets are not added explicitly, maybe there are other script lexers that need the same?

**Comment by Alexey-T** [comment]
yes, for Bash, brackets are not added and it is Ok.
