### ISSUE TITLE
no completions on new py file

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#38]
new document (saved to new.py or not - the same).
text
```
import cudatext as app
app.d|
```
no completions after `app.d`.
@veksha
branch autocomplete.cache.2.

**Comment by Alexey-T** [comment]
`$ pylsp --version
pylsp v1.5.0
`

**Comment by Alexey-T** [comment]
maybe its wrong config for LSP (new.py out of Cud's dir).

**Comment by veksha** [comment]
$ pylsp --version
pylsp v1.4.1

![image](https://user-images.githubusercontent.com/275333/192276263-bbff7e99-b8fa-4cbd-a1d4-51f17cb8f1e9.png)

**Comment by Alexey-T** [comment]
ok.
