### ISSUE TITLE
small bug with completion in Bash

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#40]
@veksha
`dbus-laun|ch` , completion, select this same command in listbox -> `dbus-dbus-launch`.

**Comment by Alexey-T** [comment]
maybe check word-chars for the current lexer? 
cudax_app.get_opt("nonword_chars") 
or hard-code '-' as word-char for Bash?

**Comment by Alexey-T** [comment]
if it is server error, let's report it to them.

**Comment by veksha** [comment]
what if you remove hyphen (minus sign) from this set of characters? (for lexer scope)
![image](https://user-images.githubusercontent.com/275333/193404436-eb43b028-96a7-4339-abc9-4a214e687853.png)

**Comment by veksha** [comment]
> maybe check word-chars for the current lexer?

it is already supported. I see in options that for bash "-" is non-word character.

**Comment by Alexey-T** [comment]
then all is Ok. solved. thanks!

**Comment by Alexey-T** [comment]
do we need to remove hyphen from nonword_chars in settings_default/lexer_bash.json ? any downside?

**Comment by veksha** [comment]
we must ask Bash experts.
