### ISSUE TITLE
"startswith" filtering

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#41]
cache branch is not using "startswith" filtering right now.
I propose to make it configurable and make "startswith" the default. so it filters the same as in main branch.
but new option will allow to switch to "in" mode (how it works in cache branch now)

**Comment by Alexey-T** [comment]
option is needed, to make is possible to use SublimeTxt 'mode'.

**Comment by Alexey-T** [comment]
in Lazarus/Delphi ide, filter is also 'in mode', and 'startswith' items are shown on the top.

**Comment by veksha** [comment]
so cache branch works like lazarus: "startswith on top", then the others.

**Comment by Alexey-T** [comment]
OK. is this issue solved?

**Comment by veksha** [comment]
not added the option yet, what will be the default?

**Comment by Alexey-T** [comment]
default - I prefer like in lazarus ('startswith' first, 'in' next).

**Comment by Alexey-T** [comment]
In code , do you check s.startswith? Better get s.find and compare result with 0, if >0 then it is item “in”

**Comment by veksha** [comment]
right now it works only in "in" mode:
```python
filtered_items = list(filter(lambda i: word1.lower() in i.label.lower(), items))
```

only sorting has "startswith":
```python
filtered_items = sorted(filtered_items,
                                    key=lambda i:
                                        (
                                        i.label == word1,
                                        word1 in i.label,
                                        i.label.lower() == word1.lower(),
                                        i.label.startswith(word1),
                                        i.label.lower().startswith(word1.lower())
                                        ),
                                    reverse=True,
                                    )
```

**Comment by Alexey-T** [comment]
okay.

**Comment by Alexey-T** [comment]
```
                                        word1 in i.label,
...
                                        i.label.startswith(word1),
```
is it conflict? 2nd condition is subcondition of 1st one.

**Comment by Alexey-T** [comment]
maybe better
```
                                    key=lambda i:
                                        (
                                        i.label == word1,
                                        i.label.startswith(word1),
                                        i.label.lower() == word1.lower(),
                                        i.label.lower().startswith(word1.lower()),
                                        word1 in i.label,
                                        ),
```

**Comment by veksha** [comment]
> maybe better
> 
> ```
>                                     key=lambda i:
>                                         (
>                                         i.label == word1,
>                                         i.label.startswith(word1),
>                                         i.label.lower() == word1.lower(),
>                                         i.label.lower().startswith(word1.lower()),
>                                         word1.lower() in i.label.lower(),
>                                         ),
> ```

your sorting:
![image](https://user-images.githubusercontent.com/275333/195471874-a30c7a16-5fe1-4848-a765-cfcb74cfe9a4.png)

current sorting (cache branch):
```
                                    key=lambda i:
                                        (
                                        i.label == word1,
                                        word1 in i.label,
                                        i.label.lower() == word1.lower(),
                                        i.label.startswith(word1),
                                        i.label.lower().startswith(word1.lower())
                                        ),
```
![image](https://user-images.githubusercontent.com/275333/195472043-f765e6e7-07a7-432b-ab7a-488ef77bf6b7.png)

you prioritize "startswith" more then "letter case".
me prioritize "letter case" more then "startswith".

sometimes you know that you want UPPERCASED words to be suggested first, so you start typing in UPPERCASE and see all of it on top of the autocompletion list. that is why i thought it would be better to prioritize "letter case".

mine with uppercase:
![image](https://user-images.githubusercontent.com/275333/195472760-94155022-fd96-4908-8cbf-80c3196857db.png)

yours with uppercase:
![image](https://user-images.githubusercontent.com/275333/195472859-8b35fa97-4de7-4592-980f-bcc34d0dc2be.png)

**Comment by veksha** [comment]
> is it conflict? 2nd condition is subcondition of 1st one.

sorry. don't understand. it is a sorting priority. it's ok to be like this. it is not a filtering.

**Comment by veksha** [comment]
> you prioritize "startswith" more then "letter case".
> me prioritizes "letter case" more then "startswith".
> (also I prioritize "in" more then "startswith")

in other words:
mine: "case" > "in" > "startswith"
yours: "startswith" > "case" > "in"

you care less about "letter case" and "in" and more focusing on "startswith",
while I think it's better when uppercased items will be grouped together on top, when needed.
all other groups will be right after them.

**Comment by Alexey-T** [comment]
okay, I did not dig into all details.

**Comment by veksha** [comment]
added option "hard_filter", please test.

**Comment by veksha** [comment]
please open new issues.
