### ISSUE TITLE
when I make untitled tab and save-as it to 'test.md'

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#44]
This is for Marksman LSP which is working - see
https://github.com/Alexey-T/CudaText/issues/4429

- I called LSP actions in test.md file (some random file) - 1st ui tab
- I made untitled tab (2nd ui tab), set its lexer to Markdown, and pasted some OK doc:
```
[reference][ref]

[ref]: url "title"
```

seems LSP is handled this untitled tab.

- I saved-as this tab to test_lsp.md. But all LSP calls show this error

![md-lsp](https://user-images.githubusercontent.com/4154978/195205475-41199f5a-907a-4b69-9ae3-09d33703f2c9.png)

@veksha

**Comment by Alexey-T** [comment]
seems client cannot handle on_save and 'convert' its data about *Untitled1 to data about filename.

**Comment by veksha** [comment]
please test my PR.

**Comment by veksha** [comment]
stop. something is not finished.

**Comment by veksha** [comment]
no. all ok.

**Comment by CudaText-addons** [comment]
okay. note - these gutter icons (linting) appears ONLY after I save-as untitled tab to new.c.
autocompletion works even before. icons - only after.

![Screenshot from 2022-10-13 06-26-58](https://user-images.githubusercontent.com/17549064/195492340-c1f2a8fb-9a19-435a-8436-48a4ba2d28eb.png)

**Comment by veksha** [comment]
> these gutter icons (linting) appears ONLY after I save-as untitled tab to new.c.

works fine for python lexer though, hm..

**Comment by veksha** [comment]
oh, it's because of an asterisk in the tab title.
when you create new tab asterisk is not yet present,
and this tab title is remembered by cuda_lsp.

we must strip it when saving tab title to dictionary..
