### ISSUE TITLE
msg_status with shortened line?

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#46]
suspect that text in msg_status is shortened too early. plugin makes len limit? can it be bigger for my big screen?

(Python Microsoft server) @veksha

![stat-ls](https://user-images.githubusercontent.com/4154978/195363626-55022912-180d-43ad-a5be-0c437d0f49b0.png)

**Comment by veksha** [comment]
```python
msg_status(f'{LOG_NAME}: {self.lang_str}: unsupported msg: {str(err)[:60]}')
```
we can make it longer then 60 (200?) and add ellipsis -> `...` when necessary.

**Comment by Alexey-T** [comment]
yes, please 100 chars and '...'

**Comment by Alexey-T** [comment]
Fixed, thanks
