### ISSUE TITLE
cache option?

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#48]
@Alexey-T
do we need option to enable/disable autocompletion cache?
(also I refactored cache branch a little more)

**Comment by veksha** [comment]
BTW, ctrl+space is not triggering on_complete if completion listbox is already visible. is it ok?

**Comment by CudaText-addons** [comment]
>is it ok?

AFAIR, ctrl+space keypress is not handled there. so yes.

options needed? as you wish, make it like Sublime.

**Comment by veksha** [comment]
added option "use_cache"

**Comment by Alexey-T** [comment]
Thanks..
