### ISSUE TITLE
Omnisharp.exe, no diagnostics

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#50]
Omnisharp.exe in Sublime has diagnostics:

![image](https://user-images.githubusercontent.com/275333/195691652-63cdc6b3-5eb6-4987-afea-373482eb5bcd.png)

CudaText has no diagnostics with Omnisharp.exe

PS: also with Omnisharp.exe you must open .cs file and press `ctrl+s` to save it, this operation will "add" this file to LSP server.
so strange, but it works the same for Sublime and CudaText.

```
"cmd_windows": ["D:\\Programm\\omnisharp\\OmniSharp.exe", "-lsp", "-z"]
```

**Comment by veksha** [comment]
### reason:
cuda_lsp compares these file paths:
file:///c:/Users/yura/Desktop/new2.cs
file:///C:/Users/yura/Desktop/new2.cs

as you can see letter case of drive is different.
is it ok to ALWAYS compare paths case-insensitive on Windows? @Alexey-T?

**Comment by veksha** [comment]
<i>
The Windows file system supports setting case sensitivity with attribute flags per directory. While the standard behavior is to be case-insensitive, you can assign an attribute flag to make a directory case sensitive, so that it will recognize Linux files and folders that may differ only by case.

This may be especially true when mounting drives to the Windows Subsystem for Linux (WSL) file system. When working in the WSL file system, you are running Linux, thus files and directories are treated as case-sensitive by default.
... (read more: https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity)</i>

**Comment by veksha** [comment]
to support case-sesitivity:
we can set only drive part to lower case, and leave other part as it is, while comparing.

**Comment by veksha** [comment]
does CudaText (on Windows) give always Uppercase for drive part?

**Comment by Alexey-T** [comment]
> does CudaText (on Windows) give always Uppercase for drive part?

no, it gives the path which it gets from OS via APIs. 

yes, OK to uppercase drive-part!

**Comment by veksha** [comment]
forgot to add if IS_WIN.
but I check for ":" character after "file:///n", so it will make it uppercase only for Windows anyways.
but you can add IS_WIN check if you want.

**Comment by CudaText-addons** [comment]
did it fix the diagnostics? how it looks now in Cud?

**Comment by veksha** [comment]
tested on Windows only:
![image](https://user-images.githubusercontent.com/275333/195708984-0a5f3a31-fed8-4da9-abc3-b36cedcc5d98.png)

**Comment by CudaText-addons** [comment]
Okay. good. can you make PR with 'IS_WIN' (I don't want to reboot and test)?

**Comment by veksha** [comment]
done
