### ISSUE TITLE
avoid color overlapping

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#53]
@veksha

https://user-images.githubusercontent.com/275333/195970279-2ad9584e-c656-472b-83a9-381fd4a47e76.png

you can avoid the overlap if you render right col without HTML colors.

**Comment by veksha** [comment]
what do you mean? i have added html tags only to left col.

"function"
"variable"
this text is not changed.

**Comment by Alexey-T** [comment]
ops.

**Comment by Alexey-T** [comment]
fixed on my side.

![Screenshot from 2022-10-15 08-59-34](https://user-images.githubusercontent.com/4154978/195971574-b5a98dec-e7e8-4d51-821c-fcd78fead4c6.png)

let's replace "function" with "func";
"variable" with "var";
"constant" with "const" ?

**Comment by veksha** [comment]
nice . yes.ok :)
