### ISSUE TITLE
shorter right column

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#54]
![Screenshot from 2022-10-15 08-59-34](https://user-images.githubusercontent.com/4154978/195971574-b5a98dec-e7e8-4d51-821c-fcd78fead4c6.png)

let's replace "function" with "func";
"variable" with "var";
"constant" with "const" ?
@veksha

**Comment by Alexey-T** [comment]
"typeparameter" with "typepar".

**Comment by veksha** [comment]
"reference" - ref?
keyword
interface
class
enummember
struct

**Comment by Alexey-T** [comment]
"reference" - ref
"keyword" - keyw
"interface" - intf
"class" - as is
"enummember" - as is
"struct" - as is

**Comment by veksha** [comment]
pushed. you can check.

**Comment by Alexey-T** [comment]
s = s.replace('interface', 'intf')
            s = s.replace('interface', 'intf')

**Comment by veksha** [comment]
fixed. thanks
