### ISSUE TITLE
3 items are duplicated here

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#56]
does ST dup them?

`    sfile = os.path.join(app_path(A|PP_DIR_DATA)`

![Screenshot from 2022-10-15 09-44-45](https://user-images.githubusercontent.com/4154978/195973332-7e921c11-ca0b-4364-b672-8964875759ba.png)

@veksha

**Comment by veksha** [comment]
![image](https://user-images.githubusercontent.com/275333/195973617-cc17ec85-f15f-4431-8668-16937316f2c9.png)
