### ISSUE TITLE
parameters not dimmed for some themes.

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#59]
@Alexey-T

color is 'ButtonFontDisabled'

zeus theme:

![image](https://user-images.githubusercontent.com/275333/195974097-a5c53668-5a57-402a-859e-5c7de67d79fe.png)

cobalt too:

![image](https://user-images.githubusercontent.com/275333/195974144-f1ea2968-7b56-4f59-a8f5-de851221c00d.png)

and brackets light:

![image](https://user-images.githubusercontent.com/275333/195974159-c6546d6b-5278-4ec0-a9a0-1f711c758db4.png)

**Comment by Alexey-T** [comment]
zeus / cobalt - fixed.
brackets lite - later.

**Comment by Alexey-T** [comment]
brackets - fixed/uploaded.

**Comment by veksha** [comment]
thanks
