### ISSUE TITLE
wrapped text looses marker color

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#64]
1. zoom-in hint window until text becomes very-very large and starts to wrap (use `shift+ctrl+space` to refresh window size after zoom)
2. if grey line will wrap on the next line it'll become black there

it is not problem with python code. because if you then zoom-out you will see that it changes back to grey when not wrapped (even without window refresh! just on mouse-wheel zoom!)
@Alexey-T

![image](https://user-images.githubusercontent.com/275333/196004996-5f2f654a-dbf4-4427-a00c-f0758ca4094e.png)

**Comment by veksha** [comment]
can't reproduce in small plugin..

**Comment by Alexey-T** [comment]
can we repro it in ui-tab editor? place long color-attr on long line with spaces. make word-wrap.

**Comment by veksha** [comment]
https://user-images.githubusercontent.com/275333/196005586-7bf41ca8-94c4-49fb-a2ef-85db52ca189f.mp4

**Comment by Alexey-T** [comment]
I understood.

**Comment by veksha** [comment]
when marker are nested inside another:

https://user-images.githubusercontent.com/275333/196006580-40b7794a-53da-4dce-a4fe-397f9d098054.mp4

**Comment by Alexey-T** [comment]
good repro. I will see at it later (n days/weeks).

**Comment by Alexey-T** [comment]
i copied the msg to Cud main Issues. closing here.
