### ISSUE TITLE
Editor.dim using?

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#65]
@veksha
https://wiki.freepascal.org/CudaText_API#Editor.dim
 is it good for func-hint? you can make pale all inactive lines.

**Comment by veksha** [comment]
```python
#cls.memo.attr(MARKERS_ADD, x=0, y=i, len=len(sig.label), color_font=cls.color_dimmed)
cls.memo.dim(DIM_ADD, i, i, 150)
```
looks OK
do you like it? 150 value ok?

![image](https://user-images.githubusercontent.com/275333/196005996-a38acd4c-114c-4ee8-98a9-d5abef778355.png)

![image](https://user-images.githubusercontent.com/275333/196006010-35085a44-dc2b-4ce5-8b27-c05b46263e74.png)

**Comment by Alexey-T** [comment]
Lets test 150 on dark themes

**Comment by Alexey-T** [comment]
yes, 150 looks good.

**Comment by veksha** [comment]
hint is not themed. do you remember?

**Comment by Alexey-T** [comment]
okay. let's use it.

**Comment by Alexey-T** [comment]
is it replacement for ed.attr() which fails on wrapping?

**Comment by veksha** [comment]
yes. and it has no such bug.

**Comment by Alexey-T** [comment]
btw, if you set 'blue' attr for this example:
'aa bb cc' 
and then it will wrap, we will loose blue on wrapping. can we add 3 attribs: for 'aa', 'bb', 'cc'?

**Comment by Alexey-T** [comment]
let's call DIM_DELETE_ALL before adding hint lines.

**Comment by veksha** [comment]
if it is called when all text is removed then it is not needed.
(as for markers: I do not delete markers, because i set text to empty str and they are removed automatically)

**Comment by Alexey-T** [comment]
test in console: dim-ranges are kept!
```
>>> ed.dim(DIM_ADD, 4,5,150)
>>> ed.dim(DIM_ENUM)
[(4, 5, 150)]
>>> ed.set_text_all('eeeeeeeeee\n'*50)
>>> ed.dim(DIM_ENUM)
[(4, 5, 150)]
```

**Comment by Alexey-T** [comment]
even here!
```
>>> ed.set_text_all('aa')
>>> ed.dim(DIM_ENUM)
[(4, 5, 150)]
```

**Comment by veksha** [comment]
and for set_text_all('') too ? # empty

**Comment by Alexey-T** [comment]
yes
