### ISSUE TITLE
cache branch merge to main

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#68]
https://github.com/veksha/cuda_lsp/tree/autocomplete.cache.2

@Alexey-T 
I think it is ready for the final test and finally be merged into main branch.

Questions:
- do I need to squash all commits to one commit?
- do we need to merge it by parts or as a whole?
I mean this branch has new features that is not related to cache, like html colors support for completion listbox or "hard_filter" option, "auto_append_bracket" option , etc...

**Comment by Alexey-T** [comment]
>do I need to squash all commits to one commit?

why to do it? no one needs cool history of commits.

>do we need to merge it by parts or as a whole?

as a whole. I welcome new features.

**Comment by veksha** [comment]
Pull request: https://github.com/CudaText-addons/cuda_lsp/pull/69

**Comment by Alexey-T** [comment]
merged, thanks!
