### ISSUE TITLE
Lua language server

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#74]
https://github.com/sumneko/lua-language-server

config:
```
{
    "lexers": {
        "Lua": "lua"
    },
    "log_stderr": true,
    "cmd_windows": ["D:\\Programm\\lua-lsp\\bin\\lua-language-server.exe"],
}
```

### problems:
- diagnostics don't work
- completion doesn't work
- signature tooltip is always dimmed

![image](https://user-images.githubusercontent.com/275333/196873207-27e90ae4-8713-43cf-bd7a-118d2c4d3a11.png)

### all these problems were fixed. Preparing pull request..

**Comment by Alexey-T** [comment]
Added the Wiki info. Tks!
