### ISSUE TITLE
Hover dialog: not all buttons are visible! (cause of `ui_scale: 125`)

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#78]
### Info:
```diff
+    OS: Windows
!    ui_scale: 125
#    ui_scale_font: 150
```

### Description

1st screenshot: you see that not all buttons are visible! (cause of `ui_scale: 125`)
2nd screenshot: my changes `'w': w * _scale_UI_percent*0.01,` (diff is below screenshots)

### Screenshots

![image](https://user-images.githubusercontent.com/275333/197315496-972c8757-06c6-4a68-8804-cb3542292aef.png)

![image](https://user-images.githubusercontent.com/275333/197315508-ce76f92f-3611-4555-b82c-67c287f0ed19.png)

```diff
diff --git a/dlg.py b/dlg.py
index 00267a7..3e63b24 100644
--- a/dlg.py
+++ b/dlg.py
@@ -186,7 +186,7 @@ class Hint:
                 'p': ed.get_prop(PROP_HANDLE_SELF ), #set parent to Editor handle
                 'x': x,
                 'y': y,
-                'w': w,
+                'w': w * _scale_UI_percent*0.01,
                 'h': h,
                 })
 

```

### Notes

I see white background is visible near last button.
we could set background of the statusbar to themed color?
or maybe you, @Alexey-T, can come up with a totally different fix?

**Comment by Alexey-T** [comment]
` w * _scale_UI_percent // 100,` is more correct.

**Comment by Alexey-T** [comment]
>we could set background of the statusbar to themed color?

OK solution.

**Comment by veksha** [comment]
> ` w * _scale_UI_percent // 100,` is more correct.

you are right. with your approach white background is no more a problem.

![image](https://user-images.githubusercontent.com/275333/197328987-76bea6e8-487c-40ab-bb42-f0f9424bf835.png)

**Comment by veksha** [comment]
need PR ?

**Comment by Alexey-T** [comment]
yes!

**Comment by Alexey-T** [comment]
maybe scale H too?

**Comment by veksha** [comment]
scaled H too. please see.
