### ISSUE TITLE
`autocomplete_commit_single_item: True` is not always working

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#82]
for example, if you have "wh" text and you press `ctrl+space` nothing happens, but it should complete it to "while" immediately.

### Reason:
When completion of single item is occurring `on_snippet` event is fired immediately.
but it is fired so fast that program's control flow is still inside of `ed.complete_alt` call, and so cached items are not yet updated (they are updating **after** `ed.complete_alt` call)

### Solution:
I need to place updating of cache data before `ed.complete_alt` call
But code needs to be refactored a little to support such fix.

**Comment by Alexey-T** [comment]
Cud py events fire from 1 thread (main). so if complete_alt is running, Cud CANNOT fire on_snippet yet.

**Comment by Alexey-T** [comment]
ops, wrong text! complete_alt is NOT an event.

**Comment by veksha** [comment]
I found out that by using simple prints to Console:

```python
def on_snippet(...
    print("def on_snippet")
    ...
```

```python
def show_complete(...
    ...
    print("before ed.complete_alt")
    ed.complete_alt('\n'.join(words), SNIP_ID, len_chars=0, selected=sel)
    print("after ed.complete_alt")
```

Console:
```
before ed.complete_alt
def on_snippet
after ed.complete_alt
```

**Comment by Alexey-T** [comment]
Right

**Comment by veksha** [comment]
is it OK that it works like that or something is not right?

**Comment by Alexey-T** [comment]
from what root function is this `def show_complete(` called?

**Comment by Alexey-T** [comment]
I mean the analysis is 'right'.

**Comment by veksha** [comment]
def on_complete

**Comment by veksha** [comment]
> if complete_alt is running, Cud CANNOT fire on_snippet yet.

but it fires as you see

**Comment by Alexey-T** [comment]
i added debug
```
    def on_complete(self, ed_self):
        print('lsp on_complete enter')
        doc = self.book.get_doc(ed_self)
        print('lsp on_complete exit')
        if doc and doc.lang:
            return doc.lang.on_complete(doc)

    def on_snippet(self, ed_self, snippet_id, snippet_text):
        """ for Editor.complete_alt()
        """
        print('lsp on_snippet enter')
        for lang in self._langs.values():
            if lang.on_snippet(ed_self, snippet_id, snippet_text):
                break
        print('lsp on_snippet exit')

```

I have 'commit single item" on.
I call ctrl+space for "whil".
```
lsp on_complete enter
lsp on_complete exit
lsp on_snippet enter
lsp on_snippet exit
```

**Comment by veksha** [comment]
`print('lsp on_complete exit')`
this line in the wrong place.

**Comment by Alexey-T** [comment]
fixed to this
```python
    def on_complete(self, ed_self):
        print('lsp on_complete enter')
        doc = self.book.get_doc(ed_self)
        if doc and doc.lang:
            res = doc.lang.on_complete(doc)
            print('lsp on_complete exit1')
            return res
        print('lsp on_complete exit2')
```

**Comment by veksha** [comment]
sorry, def on_complete is not the right place for prints. we must wait for lsp server to answer (this happens in different thread)
then after server answers we call `ed.complete_alt`

**Comment by veksha** [comment]
or it happens on Timer

**Comment by veksha** [comment]
divided "show_complete" into "prepare_complete" and "show_complete".
and fixed bug.
please test.

**Comment by Alexey-T** [comment]
Fixed, you can close this.

**Comment by veksha** [comment]
auto-closed
