### ISSUE TITLE
wiki: LSP server for Rust

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#84]
@Alexey-T, you can update wiki.

<i>[RLS](https://github.com/rust-lang/rls) has been deprecated and is no longer supported. It has been replaced with [rust-analyzer](https://rust-analyzer.github.io/). Users are encouraged to uninstall RLS and follow the instructions in the rust-analyzer manual to install it for your editor.</i>

user needs to download simple binary executable file for his system. (see https://github.com/rust-lang/rust-analyzer#quick-start)

Config that works:
```json
{
    "lexers": {
        "Rust": "rust"
    },
    "cmd_windows": ["rust-analyzer-x86_64-pc-windows-msvc.exe"],
}
```

**Comment by Alexey-T** [comment]
Updated!
https://wiki.freepascal.org/CudaText_plugins#LSP_server_for_Rust
