### ISSUE TITLE
small freeze/hiccup after choosing item in autocompletion listbox

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#87]
@Alexey-T, Have you noticed small freeze/hiccup after choosing item in autocompletion listbox?
Happens after ~2 seconds (not right after choosing an item)

Please watch video.
I hold Right arrow key after pressing Enter in listbox.
after a while cursors stops for a split second.

reproduces every time. gets annoying.
Windows.

https://user-images.githubusercontent.com/275333/197700311-6c3e87a0-9d47-42c6-a289-b2168b84be48.mp4

**Comment by Alexey-T** [comment]
Linux, Highlight_Occur plug source: no delays.

**Comment by veksha** [comment]
with empty file saved: yes
with empty tab unsaved: no

**Comment by veksha** [comment]
reproduces even after typing anything (changing document)

**Comment by Alexey-T** [comment]
windows taskmanager, its CPU usage per process, don't help?

**Comment by veksha** [comment]
it's not related to cuda_lsp. (I disabled plugin)
maybe it's related to lexer work.

**Comment by veksha** [comment]
maybe some data is writing to disk (undo data?)

**Comment by Alexey-T** [comment]
no, undo data writes together with saving.
it may be thread-related thing. lexer parser is multi-threaded. but it must be visible only on complex big files with lexer.

**Comment by Alexey-T** [comment]
maybe you know how to use disk-monitoring-tools (like SynInternals). how to see what disk actions are done during CPU peak.

**Comment by veksha** [comment]
cuda_git_status!

**Comment by Alexey-T** [comment]
uuuff, app is Ok.

**Comment by Alexey-T** [comment]
Will be solved when new event will be added.
