### ISSUE TITLE
V server?

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#88]
https://github.com/vlang/vls

@veksha
Several V users told that they will try CudaText if V server will be supported.

**Comment by Alexey-T** [comment]
My setup don't work, not completions., but server prints 1 lines to Cud LSP panel:
`VLS is early software. Please report your issue to github.com/vlang/vls if you encounter any problems.`

settings/lsp_v.json
```json
{
  "lexers": {
    "V": "v"
  },
  "tcp_port": 5007,  
  "cmd_unix": [
      "/home/user/v/v", "ls", "--socket" 
  ]
}
```

**Comment by Alexey-T** [comment]
Interesting:

![lsp2](https://user-images.githubusercontent.com/4154978/197771411-00601845-658c-45fc-8300-c48ec912e826.png)

**Comment by veksha** [comment]
Please note:
![image](https://user-images.githubusercontent.com/275333/197788609-9e4b9477-1807-4e0c-ab0f-fe30cc09399f.png)

tried in ST: different error message then in CT, but still doesn't work at all.
Windows.

**Comment by Alexey-T** [comment]
Posted to https://github.com/vlang/vls/issues/401

**Comment by veksha** [comment]
comment this line in `io_handler.py`:
```python
"Content-Type": f"application/vscode-jsonrpc; charset={encoding}",
```
because VLS doesn't support this header yet.

we will see some progress when starting the server.
**but still it doesn't work.** (in Sublime too..)

**Comment by Alexey-T** [comment]
if it doesn't work - then why to change something on my side?

**Comment by veksha** [comment]
maybe it will work on linux?

**Comment by veksha** [comment]
Progress:
- [ ] https://github.com/vlang/vls/issues/401
- [X] https://github.com/vlang/vls/issues/403

PS: 
vls is already usable if you do this:

> comment this line in io_handler.py:
> "Content-Type": f"application/vscode-jsonrpc; charset={encoding}",

**Comment by Alexey-T** [comment]
good, but I want the fully fixed V, will wait - then will upd wiki.

**Comment by veksha** [comment]
stdio mode is working for me. @Alexey-T can you confirm?
for tcp mode something is not right, i need to check..

**Comment by Alexey-T** [comment]
Maybe later i will test. can you write to a new issue the wiki info, please? if no wish, i will do it.

**Comment by veksha** [comment]
done.
