### ISSUE TITLE
autocompletion in C adds unneeded brackets

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#96]
```c
#include <stdio.h>

int main(int argc, char** argv){
    print|f("hello...");
}
```
caret in 'printf'.
autocompletion gives line
```
    printf(const char *, ...)("hello...");
```
@veksha

**Comment by veksha** [comment]
because it is lsp Snippet format, not a plaintext. do you suggest we delete "(const char *, ...)" from Snippet before insertion?
if snippet is single-line and has brackets and we see "(" ahead.

**Comment by Alexey-T** [comment]
yes, we may delete `(...)` before insertion if after the caret - only wordchars and then `(`.

**Comment by Alexey-T** [comment]
How ST4 does it?

**Comment by veksha** [comment]
sorry, it was already supported, but only if caret is next to "(".
i need to seek for "(" not only near caret.
I'll see..

**Comment by veksha** [comment]
i guess ST4 is not that smart.

**Comment by veksha** [comment]
another bug:
Java
```java
public class Example {
    public static void main(String[] args) {
        mai|n();
    }
}
```
autocompletion gives: `main);`

**Comment by veksha** [comment]
fixed, please test PR.

**Comment by Alexey-T** [comment]
```
'\(([^)]*)\)$'
```
this RE equals to (seems)
```
'\(.*?\)$'
```

**Comment by veksha** [comment]
![image](https://user-images.githubusercontent.com/275333/198881643-f520d794-3184-4334-bab2-b2466258e352.png)

**Comment by Alexey-T** [comment]
seem you tested on bad site!
cud shows this

![Screenshot from 2022-10-30 16-43-42](https://user-images.githubusercontent.com/4154978/198881812-6daaab58-f4cc-42bc-a9e9-5d6a3555a816.png)

**Comment by Alexey-T** [comment]
ah, right, because of $ char.

**Comment by veksha** [comment]
but can be simplified to `\([^)]*\)$`
capturing group is not needed.

**Comment by Alexey-T** [comment]
I noted it too, but didn't tell
