### ISSUE TITLE
is macro "${fdir}" still working ok?

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#97]
@veksha Please see comments from https://github.com/Alexey-T/CudaText/issues/4423#issuecomment-1293404263
User told me the ${fdir} doesn't work.

**Comment by veksha** [comment]
is see in wiki that this macro is working for Snippets plugin.
where do you see it must work for LSP ?

**Comment by Alexey-T** [comment]
I don't remember. sorry,closing.

**Comment by Alexey-T** [comment]
Im not sure - what is better to better support java server, which needs 2 folder params (or 1 folder param)?
