### ISSUE TITLE
Java server cfg

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#98]
@veksha
do we need config
```
  "cmd_windows": [
      "D:\\testlsp\\ctrun2.bat","D:\\testlsp\\work", "D:\\testlsp\\work"]
```
ie 2 fixed folder params after BAT file,
 OR we need one param "." like you show here -
https://github.com/Alexey-T/CudaText/issues/4423#issuecomment-1292099645
?

**Comment by veksha** [comment]
we need to provide two folders for bat file, (work dir, cache dir.)
i just noticed it works with providing one path only.

**Comment by Alexey-T** [comment]
Pls review
https://github.com/Alexey-T/CudaText/blob/master/app/readme/wiki/cudatext_plugins.wiki#L1746

**Comment by veksha** [comment]
have you managed to configure java lsp on your system, @Alexey-T?
we need to make sure everything works.
i noticed that only autocompletion works. but not other features.

**Comment by Alexey-T** [comment]
On Ubuntu - not yet, I need Shell script instead of BAT file. on Win10 - not yet

**Comment by veksha** [comment]
"Make sure Java in installed"
typo

**Comment by Alexey-T** [comment]
fixed

**Comment by Alexey-T** [comment]
```
C:\Java\jdt-language-server\config_win>java -version
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)
```

**Comment by Alexey-T** [comment]
aha. thanks! I had OLD OLD jave on pc. and updated via UPDATER. will get OK java.

**Comment by veksha** [comment]
i see in log:
<i>org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.common [28]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"</i>
  
so maybe it wants 11 minimum.

**Comment by Alexey-T** [comment]
reinstalled from java.com. it is version 1.8.0.xxxx again! where to get v11?

**Comment by Alexey-T** [comment]
I found Java 11 - https://www.codejava.net/java-se/download-and-install-java-11-openjdk-and-oracle-jdk

>For Windows, I recommend to download the file jdk-11.0.7_windows-x64_bin.exe. Note that you must have an Oracle account to be able to download JDK 11 installer. If not, creating one is free.

it needs account - bad.

**Comment by veksha** [comment]
don't remember where i got openjdk.
meanwhile try this: https://jdk.java.net/java-se-ri/11

**Comment by veksha** [comment]
https://adoptopenjdk.net/

**Comment by Alexey-T** [comment]
I found it. here.
https://www.oracle.com/java/technologies/downloads/#jdk19-windows
it is 19 !
LSP works - autocompletion appears after 1-2 tries.

**Comment by Alexey-T** [comment]
@veksha I just saw ur message about "simpler BAT file for Java lsp" but Github UI is strange - i lost it. post here.

**Comment by veksha** [comment]
@Alexey-T this PR: https://github.com/CudaText-addons/cuda_lsp/pull/103

**Comment by veksha** [comment]
this PR is about better header parsing (and using my simpler BAT file for testing it)

**Comment by veksha** [comment]
please merge it locally and test for some time too.
- it must log non-header lines correctly (echo lines with text and empty echo lines)
- it must not freeze/hang

**Comment by Alexey-T** [comment]
I cannot it test while Im in the Ubuntu...

**Comment by veksha** [comment]
I think you can adapt cmd file to linux easily.
do you have Java installed on Ubuntu?

**Comment by Alexey-T** [comment]
yes, I have

**Comment by veksha** [comment]
Converting DOS Batch Files to Shell Scripts
https://tldp.org/LDP/abs/html/dosbatch.html

**Comment by veksha** [comment]
```
:: language server config folder location
set Config=%Directory%/config_win
```
and here `config_win` change to `config_linux`

**Comment by Alexey-T** [comment]
I am lazy to study shell scripts. :( so please help me to make it.

**Comment by veksha** [comment]
LOL.
try this:
```bash
#!/bin/bash
echo
echo Usage: jLSP.sh CacheDir
echo where "CacheDir" is an absolute path to your data directory. eclipse.jdt.ls stores workspace specific information in it. This should be unique per workspace/project.
echo

# language server installation folder (adjust to suit)
Directory=~/jdt-language-server
# language server jar file (update based on version file of jar)
JarFile=$Directory/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
# language server config folder location
Config=$Directory/config_linux

CacheDir=$1
echo Directory: $Directory
echo   JarFile: $JarFile
echo    Config: $Config
echo  CacheDir: $CacheDir

java -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dlog.level=ALL -noverify -Xmx1G -jar $JarFile -configuration $Config --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -data $CacheDir

```

**Comment by veksha** [comment]
config:
```
{
  "lexers": {
    "Java": "java",
  },
  "cmd_unix": ["~/jLSP.sh", "./cache_for_proj1"],
}
```

**Comment by Alexey-T** [comment]
I removed java - to use OpenJDK now. and all ok, it works! great! posting wiki update.

**Comment by RESDXChgfore9hing** [comment]
Nice BTW the other features in intellisense other than autocompletion not working is expected?or is it perhaps server problem?

**Comment by Alexey-T** [comment]
Java - also linting works (as I see gutter icons from linting).

**Comment by veksha** [comment]
other features must work with latest `cuda_lsp`. did you update?

**Comment by RESDXChgfore9hing** [comment]
yeah 1.74 if not wrong.

**Comment by RESDXChgfore9hing** [comment]
linting?is the exclamation mark at the line row linting >
!(yellow color)

**Comment by veksha** [comment]
yes. it is diagnostics.

**Comment by Alexey-T** [comment]
update the LSP plugin, from 'plugins / addons manager / update' dialog. if not done yet.

**Comment by RESDXChgfore9hing** [comment]
i clicked and my god cudatext froze.force shut down and retry ok.
I dont think it actually shows the definition?when I highlight "System"and right click>definition.
I dont see error now unlike before but I also dont see any explaination?

**Comment by RESDXChgfore9hing** [comment]
doing it on my local custom function works though

**Comment by Alexey-T** [comment]
(I guess that Java server froze, and plugin waits for it)

**Comment by veksha** [comment]
![image](https://user-images.githubusercontent.com/275333/199278850-7defa31d-9fe5-4b4f-af36-fb1ce7ae46cc.png)

**Comment by RESDXChgfore9hing** [comment]
no wayyy.

**Comment by RESDXChgfore9hing** [comment]
ohh wait
click on it then click plugin>lsp>hover

**Comment by RESDXChgfore9hing** [comment]
and that poped up,i guess it not *realtime* hover but ok.I can accept that.

**Comment by Alexey-T** [comment]
(for the hover, hold Ctrl and hold mouse over id for 2 sec)

**Comment by RESDXChgfore9hing** [comment]
not sure how to do that.highlight text and then ctrl 2 sec?

**Comment by Alexey-T** [comment]
- hold Ctrl key
- move mouse over 'System' , stop moving, and wait 1-2 secs

**Comment by veksha** [comment]
@RESDXChgfore9hing Personally I mapped `hover` to F1 and set "enable_mouse_hover": to `false` in cuda_lsp config

**Comment by RESDXChgfore9hing** [comment]
is the ctrl and move mouse to keyword .feature listed in wiki?
It would be great to have a list of default way to use all of the lsp features.

**Comment by RESDXChgfore9hing** [comment]
hmm noted.I am dumb then for not reading the readme.sorry

**Comment by veksha** [comment]
> I dont think it actually shows the definition?when I highlight "System"and right click>definition.

@RESDXChgfore9hing 
java lsp server must know where to look for source files and scan them, before it can take you to definition of "System".
if you really need this, i can teach you how to do that.

small demo that it works:

https://user-images.githubusercontent.com/275333/199291302-b5d80210-8fec-4f91-8563-162947cccf66.mp4

**Comment by RESDXChgfore9hing** [comment]
huh nice .what is the way to set the java root for the lsp or is it for cudatext specific?

**Comment by veksha** [comment]
@RESDXChgfore9hing, sorry this was wrong info. it worked because I opened System.java file and server remembered/cached it.
but to make it really work Cuda_lsp must implement support for **non-standard** LSP methods (like `java/classFileContents`)


more info: https://github.com/eclipse/eclipse.jdt.ls/issues/2306

<i>... your client needs to implement support for opening .class files via the [java/classFileContents](https://github.com/eclipse/eclipse.jdt.ls/wiki/Language-Server-Protocol-Extensions) command, for which we need better doc, obviously, but you can see some hints at the vscode-java implementation: https://github.com/redhat-developer/vscode-java/search?q=ClassFileContentsRequest</i>

**Comment by RESDXChgfore9hing** [comment]
if its non standard then i guess we can keep it as a low priority target.since its definitely going to be less useful.
I can see it only being useful for using crappy 3rd library with horrible javadoc formatting or javadoc that just doesnt have any explaination.
